fix extends instructions
Existing instructions cause a error on zola check
Error: Template 'index.html' is inheriting from 'themes/zola-clean-blog/templates/index.html', which doesn't exist or isn't loaded.

Knocking off themes lets the path resolve